### ISSUE TITLE
Listar defesas agendadas dada uma unidade

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#105]

**Comment by lfloro** [comment]
@thiagogomesverissimo aqui na fea-RP, a data de defesa só é preenchida no Janus após a defesa realmente acontecer. Talvez seja assim também em outras unidades?

**Comment by alecostaweb** [comment]
Aqui na ECA fiz uma consulta
SELECT * FROM ECA.dbo.AGPROGRAMA WHERE dtadfapgm >= '2019-6-27' e retornou somente 3 registros de hoje, dia 27/6. Vou confirmar com o serviço de Pós

**Comment by alecostaweb** [comment]
Acabei de falar com o serviço de Pós aqui na ECA e segundo eles o campo data da defesa só é preenchido no dia da defesa porque essa data sofre várias alterações e este campo só é necessário por conta da Ata de defesa. A Ata de defesa só é liberada um dia antes da defesa. @thiagogomesverissimo, acredito que isso seja procedimento padrão nas unidades e desta forma não vai rolar visualizar somente as defesas que já aconteceram.

**Comment by masakik** [comment]
Aqui na EESC temos o sistema da papelada (do JEF) que dentre outras coisas publica em webservice as datas das defesas agendadas e que tenham sido autorizadas a publicação. Faz parte do sistema que tramita a papelada da POS daqui.

**Comment by thiagogomesverissimo** [comment]
Então não real a função de agendamento no Janus não é usada como agendamento, pois é preenchida pós defesa.
