### ISSUE TITLE
na classe bem patrimoniado implementar filtro de busca no método ativos

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#131]
por exemplo para filtrar por codpes ou por codlocusp.

**Comment by masakik** [comment]
Nesse sentido poderia implementar dois parâmetros opcionais tipo array onde um seria filter e outro search. Os dois arrays teriam o par coluna=valor sendo que no filter a consulta utiliza coluna=valor e no search utiliza coluna like '%valor%'. Com isso poderia fazer busca por nome, modelo ou filtrar por local, setor, responsável e todo o tipo de combinação que quiser.
Idéias?????

**Comment by thiagogomesverissimo** [comment]
Seria ótimo!

**Comment by lfloro** [comment]
@masakik @thiagogomesverissimo  tentei utilizar apenas um array para filtrar os resultados verificando o tipo do valor, seguindo a ideia de que se o valor for "int" deve ser exato, por exemplo o codpes, codlocusp, etc; e se for string utilizar o LIKE, por exemplo modelo (modpat), marca do bem (epfmarpat), etc. Ainda, se for passado mais de um campo no array, utilizar operador 'AND' por padrão ou receber na chamada da função. O que acham?
