### ISSUE TITLE
Porque query fica dividido em várias linhas?

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#143]
As várias linhas concatenadas, ok. Mas se simplesmente quebrar as linhas sem concatenar o sql vai ficar meio poluido mas fica mais fácil de dar copy e paste do dbeaver e vice versa, para os testes e deploy. No commit 2bcf506 eu fiz assim pra vcs verem. Achei que fica melhor.

**Comment by alecostaweb** [comment]
Eu prefiro tbm :+1:

**Comment by masakik** [comment]
Legal

**Comment by fabiojm** [comment]
Também prefiro !! :neckbeard:

**Comment by masakik** [comment]
Colocado como recomendação na documentação
