### ISSUE TITLE
Integração contínua, phpunit, PSR-2 e análise de código

### ISSUE THREAD

**Issue by enricodias** [uspdev/replicado#179]
Encontrei esse repositório enquanto procurava por novos projetos no github para contribuir.

Existe algum motivo específico para vocês não estarem usando phpunit para testes unitários, alguma ferramenta de integração contínua como Travis-CI, alguma ferramenta de análise de código como Codacy e um padrão de código bem definido como o PSR-2?

**Comment by thiagogomesverissimo** [comment]
@enricodias,

Obrigado pelo interesse. Esssa lib depende de uma estrutura de tabelas que não é controlada por nós e e  em um banco de dados que não sei se o travis-ci aceita (sybase). Mas sim, temos alguns códigos de testes https://github.com/uspdev/replicado/tree/master/test mas ainda não usamos o phpunit (usar php unit em /tests)
