### ISSUE TITLE
Unificar as consultas para funcionar nos difrentes SGBD's replicados

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/replicado#18]

**Comment by masakik** [comment]
Quais seriam os SGBDs? Aqui usamos Windows server.

**Comment by thiagogomesverissimo** [comment]
acho que já funciona em todos, não?

**Comment by alecostaweb** [comment]
Só ouvindo nossos colegas com outros SGBD's. Caso algo não funcione, New Issue...

**Comment by thiagogomesverissimo** [comment]
Feito em https://github.com/uspdev/replicado/pull/243
