### ISSUE TITLE
Nos métodos que listam grande volume de dados, implementar paginação

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#181]

**Comment by masakik** [comment]
Acho que em novos métodos deveríamos colocar o limite por padrão, com a possibilidade de fornecer parâmetro para alterar o limite.

**Comment by ezanon** [comment]
Anotando como faz limits no sql server... eu só sabia no mysql... 
Depois de ORDER BY... 
`offset 100 rows fetch next 300 rows only`
, assim começa no registro 100+1 exibindos os próximos 300... 
Então pra exibir os 300 primeiros:
`offset 0 rows fetch next 300 rows only`

**Comment by thiagogomesverissimo** [comment]
Sabe se funciona no sybase da mesma forma?

**Comment by thiagogomesverissimo** [comment]
Testei não funciona. No sybase somente com procedure. Assim, estou fechando a issue, pois não existe uma solução genérica para mssql e sybase. O melhor é usar cahce mesmo.
