### ISSUE TITLE
Na classe Pessoa e no métdodo ativosVinculo tratar o charset para $vinculo

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/replicado#193]
No MS Sql Server (ECA): 
'vinculo'       => $vinculo,

No Sybase (IF)
'vinculo'       => iconv('UTF-8', 'ISO-8859-1', $vinculo),

@thiagogomesverissimo, veja qual é o seu cenário e teste por favor

**Comment by thiagogomesverissimo** [comment]
Essa opção funcionou aqui, e deveria (explico porque abaixo):
`'vinculo' => iconv('UTF-8', 'ISO-8859-1', $vinculo),`

No lado das nossas aplicações, trabalhamos sempre em UTF8 e a ideia da biblioteca PHP replicado é justamente abstrair o fato do servidor USP usar ISO-8859-1. Assim, a biblioteca  receber tudo em UTF-8 e devolve tudo em UTF-8, internamente nas classes fazemos os tratamentos do ISO-8859-1. Se no SQL server funcionou sem essa linha, das duas uma:

 - Você não fez um teste com string acentuada
 - ou o SQL server converteu na calada da noite para você a string que estava em UTF8 para ISO-8859-1

De qualquer maneira, essa linha `'vinculo' => iconv('UTF-8', 'ISO-8859-1', $vinculo),` não quebra sua consulta, quebra?

**Comment by alecostaweb** [comment]
Sim, quebra.
![image](https://user-images.githubusercontent.com/10613364/71252945-27565780-2305-11ea-9203-4d13c40c9472.png)

**Comment by alecostaweb** [comment]
Sugestão do @thiagogomesverissimo , criar uma variável no .env da aplicação REPLICADO_SGBD podendo ser mssql ou sybase
Receber no método o $sgbd e antes de setar os parâmetros
$vinculo = ($sgbd == 'mssql') ? $vinculo : iconv('UTF-8', 'ISO-8859-1', $vinculo);
