### ISSUE TITLE
Na classe úteis, implemetar um método que converte um array em um string formatada em csv

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#2]
algo do tipo:
```
$r = "";
foreach($array as $i) {
    $r .= implode(",", $i) . "\r\n";

}
```
Porém, neste método receber o array com os nomes das colunas

**Comment by leandroramos** [comment]
Pelo que pude ver nos códigos, o array possui apenas uma linha (uma pessoa, por exemplo). O código do método deve contemplar também os casos em que o resultset for retornar mais de uma linha?

**Comment by thiagogomesverissimo** [comment]
Sim. Mas essa conversão para csv será usada em outros métodos (ex: todos alunos de graduação ativos)

**Comment by leandroramos** [comment]
Beleza. Eu fiz um que funciona com apenas uma linha. Mas amanhã vou subir a PR para várias linhas.

**Comment by leandroramos** [comment]
Vou implementar diferente porque quando vem uma linha, é um array (ou dicionário) de $chave => $valor, mas quando vem um um resultset de várias linhas é um array de arrays $chave => $valor.

**Comment by thiagogomesverissimo** [comment]
Sim, vai chegar um array de array para.ser convertido.

**Comment by girol** [comment]
Vocês tentaram isso?

http://php.net/manual/en/function.fputcsv.php

**Comment by leandroramos** [comment]
Eu vi. Não usei ainda porque quero ver se a ideia é só gerar string formatada mesmo.
