### ISSUE TITLE
Nao retornar mensagens de erro.

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#200]
A ideia é que as mensagens fique por conta da aplicação. Então a api retornaria o resultado, array vazio ou false. Se for o caso de ser necessário algum retorno de erro retornar códigos tipo return 1, return 2, etc.
Estou agindo essa issue para discutirmos se isso seria uma recomendação legal para se incorporar na documentação.

**Comment by thiagogomesverissimo** [comment]
Acho  que seria uma mudança ótima.  Podemos partir para alterar todos métodos.

**Comment by alecostaweb** [comment]
Seria muito bom! Gostei da susgestão do Robson com um campo 'response', com boolean, e um campo result, com o resultado.
Só para registro vou relatar um fato:
O método Graduacao::curso retorna o curso e habilitação de um aluno de graduação ativo. Ocorreu que a consulta query/fetch retornou false. Como assim??? Sim, havia um aluno de graduação ativo, porém vinculado a um curso já desativado. Pode isso??? Sim, porque este aluno que se formou a muito, muito tempo atrás fez uma solicitação de documentos e a pedido da graduação da unidade foram carregados dados do antigo sistema Kyron, e uma vez feito isso o aluno surgiu como ativo no replicado. Depois de atender a solicitação do antigo aluno ele deixa de ser ativo no Júpiter.
Detalhe, o erro dentro do próprio método, uma vez que alguns métodos da classe Uteis não estão preparados para tratar um array false.
