### ISSUE TITLE
Conexão com banco definindo charset=utf-8

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#206]
Ao invés de 
$dsn = "dblib:host={$host}:{$port};dbname={$db}";
usar
$dsn = "dblib:version=7.0;charset=UTF-8;host={$host}:{$port};dbname={$db}";

Isso implicaria em alterar todos os métodos para não mais usar utf8_converter ????
Meu replicado é windows, seria diferente se fosse sybase ???

**Comment by thiagogomesverissimo** [comment]
Vou testar em linux com sybase, mas acho que não rola não...

**Comment by thiagogomesverissimo** [comment]
charser resolvido em: https://github.com/uspdev/replicado/pull/243

dblib não pode ser fixada, pois sybase e mssql usam versões diferentes. Melhor cada um configurar no seu tds particular.
