### ISSUE TITLE
A função nomeCompleto($codpes) está retornando um array, deveria ser string

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#211]
```
array:1 [
  "nompesttd" => "Fulano"
]
```

**Comment by alecostaweb** [comment]
Essa mudança será impactante

**Comment by alecostaweb** [comment]
Além do que nem seria necessária a função, uma vez que tem a função dump

**Comment by alecostaweb** [comment]
Se for mudar, sugiro eliminar a função nomeCompleto e utilizarem Pessoa::dump($codpes)['nompesttd']

**Comment by alecostaweb** [comment]
Tem como criar um alerta para quem utiliza a função nomeCompleto?

**Comment by masakik** [comment]
Seria legal se conseguissemos padronizar algumas coisas. Talvez numa versão 2 com quebra de compatibilidade retroativa?

**Comment by thiagogomesverissimo** [comment]
Acho que podemos mantê-la, pois

`nomeCompleto($codpes) `

é mais bonito que

`Pessoa::dump($codpes)['nompesttd']`

**Comment by thiagogomesverissimo** [comment]
Mas de qualquer modo, vamos seguir a premissa.  Não quebrar e se quebrar, fazer palnejado. Talvez vale a pena mesmo ter um padrão de desenvolvimento dessa lib.
