### ISSUE TITLE
Classe Gênero: consultas que retornam a quantidade de pessoas ativas por gênero

### ISSUE THREAD

**Issue by gabrielareisg** [uspdev/replicado#217]
Métodos que retornam a quantidade de alunos ativos na graduação, ativos por curso de graduação e docentes ativos por gênero.

**Comment by masakik** [comment]
Não seria melhor que esse método fosse junto à classe pessoa ou à classe graduação? Na verdade as contagens de aluno de graduação ficariam na classe Graduacao e os outros dois na classe Pessoa. 
Também quero sugerir os nomes dos métodos: Graduacao::contarAtivosPorGenero, Graduacao::contarAtivosPorCursoGenero, Pessoa::contarDocentesAtivosPorGenero, Pessoa::contarEstagiarioAtivoPorGenero.
Dessa forma fica mais claro o escopo do método.
Mais uma coisa, não seria melhor injetar o código da unidade por variável de ambiente? Inclusive com a possibilidade de injetar mais de uma unidade na forma de lista, que deve ser o caso da FFLCH. 
O que vc acha @thiagogomesverissimo ?

**Comment by masakik** [comment]
Graduacao::contarAtivosPorCursoGenero e Graduacao::contarAtivosPorGenero talvez possam ser fundidos em um único método, sendo o codcur opcional.

**Comment by thiagogomesverissimo** [comment]
Perfeito. Tinha conversado com a Gabriela e ela realmente ficou na dúvida onde colocaria esses métodos. As sugestões são boa. Precisa de um help Gabriela? 

Sobre a unidade, ótima ideia. Assim os métodos valem sempre por contexto. Tem muitos métodos que recebem a unidade como parâmetro?

**Comment by masakik** [comment]
tem um tanto. Mas mexeriamos nos novos metodos e os antigos ficariam para a versão 2 do replicado pois quebraria a compatibilidade.
