### ISSUE TITLE
Criar teste unitário para verificar qualidade de código (travis)

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#225]
- [ ] Verificar se existe annotation
- [ ] Verificar se há a descrição na primeira linha (até linha em branco)
- [ ] Verificar se tem @return
- [ ] Verificar se não tem tab
- [ ] verificar espaçamento múltiplo de 4

**Comment by thiagogomesverissimo** [comment]
https://github.com/nikic/PHP-Parser

**Comment by masakik** [comment]
estes testes unitários são com phpunit?

**Comment by thiagogomesverissimo** [comment]
movendo para roadmap
