### ISSUE TITLE
Vamos usar REPLICADO_CODUNDCLG  ou REPLICADO_CODUND para código da unidade?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#227]

**Comment by masakik** [comment]
Não entendi.

**Comment by alecostaweb** [comment]
Isso resolveria casos como professores de pós de outra unidade?

**Comment by thiagogomesverissimo** [comment]
Eu estava olhando uma versão antiga e em algum momento usávamos REPLICADO_CODUND e agora usamos REPLICADO_CODUNDCLG. Mas tá tudo certo, fiz um grep aqui e todos métodos usam REPLICADO_CODUNDCLG agora.

**Comment by thiagogomesverissimo** [comment]
Resolveria sim, sem problemas.
