### ISSUE TITLE
Criar método que lista docentes de uma unidade por departamento solicitado

### ISSUE THREAD

**Issue by ezanon** [uspdev/replicado#237]
Método novo utilizando código da unidade definido no putenv, com opção de selecionar o departamento.
Método docentes() será deprecado.

**Comment by thiagogomesverissimo** [comment]
Como o método docentes poderá ser chamado diversas vezes no mesmo sistema, acho que o .env não é um bom lugar. 
Parâmetro não seria melhor :
`docentes($departamento=null) `

**Comment by ezanon** [comment]
Sim! Essa é a ideia mesmo... estou fazendo listarDocentes($codset=false)

**Comment by ezanon** [comment]
Não pensei nisso. Acho que seria uma outra questão, uma outra issue, não?
