### ISSUE TITLE
Verificar todos métodos que usam REPLICADO_CODUNDCLG para aceitarem mais que uma unidade

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#240]

**Comment by ezanon** [comment]
Sim, mas a consulta tem que ser compatível com isto. Por exemplo:

putenv('REPLICADO_CODUNDCLG=44,43,28');  // sem aspas nos números!

Mas o WHERE tem que usar IN e obter o valor usando getenv atribuindo a uma variável:

$unidades = getenv('REPLICADO_CODUNDCLG');
$query = " SELECT * FROM LOCALIZAPESSOA WHERE codundclg IN ({$unidades}) "

**Comment by thiagogomesverissimo** [comment]
vou mudar o título da issue para mudarmos os métodos que usam REPLICADO_CODUNDCLG para receber diversar unidades
