### ISSUE TITLE
Ao criar um novo método é legal colocar o autor

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#251]
na documentação do código, tipo
 * por João da Silva - js@usp.br

Se sim, é o caso de colocar isso na documentação sobre recomendações

**Comment by masakik** [comment]
que qualquer dúvida perguntamos ao autor original :1st_place_medal:

**Comment by thiagogomesverissimo** [comment]
Eu acho desnecessário... para isso serve o commit

**Comment by thiagogomesverissimo** [comment]
Mas é uma opinião pessoal. Pois vai mudando a parada muito,  ainda mais nesse projeto.

**Comment by thiagogomesverissimo** [comment]
mas não sou contra também;

**Comment by thiagogomesverissimo** [comment]
Se bem que relendo seu comentário,  parece interessante mesmo consultar a pessoa que fez o método.  Enfim, pode ser uma orientação opcional.

**Comment by thiagogomesverissimo** [comment]
Vamos colocar sim essa orientação.  Você sabe como fica o parametro de autor?
@Autor ?
