### ISSUE TITLE
Criar um campo para prefixo das tabelas, no caso de unidades que recebem views nao diretamente da sti

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#28]

**Comment by masakik** [comment]
O prefixo entraria na configuração tipo
putenv('REPLICADO_TBL_PREFIX=prefix_'); ?
e na consulta ficaria 
$prefix = getenv('REPLICADO_TBL_PREFIX');
...
" SELECT {$cols} FROM ".$prefix."PESSOA WHERE codpes = {$codpes}"; ?

**Comment by alecostaweb** [comment]
Passando o prefixo como parâmetro fica mais flexível.

**Comment by masakik** [comment]
O prefixo muda por aplicação. Então não teria problemas ser em variavel de ambiente. Mas como parâmetro fica mais flexivel mesmo.

**Comment by thiagogomesverissimo** [comment]
Ainda é necessária essa issue?
Pelo que entendi o @masakik agora acessa o replicado sem passar por views intermediárias.

**Comment by masakik** [comment]
Não precisa mais :smile:
