### ISSUE TITLE
método pessoa::nome não deveria usar _ no lugar de acentos?

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#284]
por ex se $nome = 'joão', buscaria por 'jo_o' e não 'joao'

**Comment by masakik** [comment]
Vou aproveitar e padronizar o nome do método em Pessoa::procurarPorNome($nome, $fonetico=true, $ativos=true), assim pode substituir o nome() e nomeFonetico()

**Comment by thiagogomesverissimo** [comment]
Perfeito,  acho que pode mudar
