### ISSUE TITLE
PDO::FETCH_OBJ não seria melhor que PDO::FETCH_ASSOC no fetch e fetchAll?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#346]

**Comment by thiagogomesverissimo** [comment]
Lembrando que isso impactaria numa grande mudança. Mas há os que preferem objetos ao invés de array...

**Comment by masakik** [comment]
e se colocar um parametro opcional tipo no env que modifica a saída para objeto?

**Comment by thiagogomesverissimo** [comment]
ok, vou pensar sobre.
Tem a questão dos UTF8 converts que teria que ser alterada;

**Comment by masakik** [comment]
A idéia é retornar para o usuário um objeto ao invés de array? Ou trabalhar internamente com objeto também?
De qualquer forma, se o método retorna o fetch direto tranquilo, mas para os métodos que trabalham com os dados antes de retornar aí fica mais complicado. Uma opção seria criar um método de formatação da saída e todos os outros métodos chamar ele. Daria para ir implementando conforme a necessidade.

**Comment by masakik** [comment]
apesar que o json_decode(json_encode($arr)) não funciona?

**Comment by thiagogomesverissimo** [comment]
Nao sei ainda qual melhor solução.  Mas eu percebi que fico convertendo para objeto um monte de array que ja poderiam ser objetos. Mas no todo daria muito trampo, talvez seja melhor deixar para a aplicação resolver.

**Comment by thiagogomesverissimo** [comment]
Fiz uns testes aqui. Seria uma mudaça muito impactante. Melhor deixar com a aplicação mesmo.
