### ISSUE TITLE
Adicionar verificação antes de salvar arquivo XML Lattes

### ISSUE THREAD

**Issue by lfloro** [uspdev/replicado#347]
Em alguns casos parece que o campo imgarqxml está "corrompido" gerando um zip "corrompido" e/ou vazio e assim salvando um arquivo XML também vazio.

**Comment by thiagogomesverissimo** [comment]
Você percebeu problemas com timeout?
Pergunto pq temos um sistema que localmente na nossa máquina com internal PHP server baixa de boas o XML. Mas na produção com apache2 não. Vou investigar direito, mas acho que é algo com o timeout talvez.

**Comment by lfloro** [comment]
Com timeout não. Eu fiz observação sobre registro corrompido, porque tentando fazer um processo de extração "manual" diretamente com o registro também tive problema.

**Comment by thiagogomesverissimo** [comment]
Beleza.
Vou investigar aqui o que ocorre =)
