### ISSUE TITLE
Novo método Pessoa::listarAtivosSetor(array $codset)

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/replicado#391]
Listar as pessoas ativas (e também aposentados) por setor, onde $codset é um array de um ou mais setores.
Será utilizado incialmente no uspdev/pessoas para busca por setor.

**Comment by masakik** [comment]
Aqui são docentes e não docentes?
Já tem um metodo para docentes listarDocentes que tem opção de setor e tem um de servidores, sem opção de setor.
Acho que não incluirá alunos então seria bom nomear listarServidoresAtivosPorSetor($setores)

**Comment by alecostaweb** [comment]
Sim.
Como a busca por pessoas é por setor tende a trazer docentes, funcionários e estagiários.
No uspdev/pessoas o próximo passo é trazer por vínculo.

**Comment by alecostaweb** [comment]
Quanto ao nome, sim, mas pode ser listarServidoresAtivosSetor? Tendo somente o verbo já ajuda né?

**Comment by masakik** [comment]
sim

**Comment by masakik** [comment]
dúvida: o método está trazendo os inativos também, é isso mesmo? Se sim deveria ter outro nome.

**Comment by alecostaweb** [comment]
@masakik tem certeza que traz os inativos?
