### ISSUE TITLE
Na classe Graduacao, criar método para retornar o historio escolar do aluno

### ISSUE THREAD

**Issue by fabiojm** [uspdev/replicado#40]

**Comment by alecostaweb** [comment]
Então... Pedi ao Serviço de Graduação da ECA um histórico de aluno emitido pelo JúpiterWeb para ver como é. O histórico vem com autenticiadade via sistema USP Webdoc. Pensando nisso, se o Webdoc tivesse uma API que retornasse o histórico de forma restrita com credenciais de acesso como é feito no WSBoleto, então não teríamos que reinventar a roda.

**Comment by alecostaweb** [comment]
Vendo o histórico de um aluno:
- A primeira página traz os dados acadêmicos do aluno, aqui já temos um método que poderá mudar de nome e se acrescentar as coisas que faltam.
- Nas outras páginas tem as disicplinas cursadas com as notas, créditos, carga horária, status, etc.
- No final, tem totais e legendas.
Separando as coisas, vou tentar algumas consultas sql a partir do nº USP do aluno.

**Comment by alecostaweb** [comment]
@fabiojm criei um método na classe Graduacao chamado disciplinasConcluidas que traz o código da disciplina, o status e o nº de créditos aula. Criei este método para uma necessidade do uspdev/ccg, mas ele pode ser utilizado também no histórico do aluno. Veja o readme.md aqui do replicado e teste esta classe, pode ser um começo para o histórico do aluno.
