### ISSUE TITLE
metodo obterAtivosPorArea não está funcionando

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#412]
também é repetido do método alunosPrograma

- Seria legal usar o env REPLICADO_CODUNDCLG ao invés de passar por parâmetro
- quando o retorno é uma lista o método deveria começar com listarXXX, nesse caso listarAlunosAtivosPrograma ou no caso do alunosPrograma serai listarAlunosAtivosProgramaArea
- se o retorno é uma lista nãodeve retornar null e sim um array vazio (gabrielareisg)

Erickson, ao invés de fazer um loop, não seria possivel utilizar "V.codare IN ( implode(',', $codares) )" ??
Thiago, se puder passa pra Gabriela ver o método dela. 
@gabrielareisg

**Comment by thiagogomesverissimo** [comment]
Eu renomei o método da Gabriela, peguei a unidade do env e retornie array nulo aqui: https://github.com/uspdev/replicado/commit/5a8b3f634f13cce8dc87bdd265668fbf6b00e3f5

Mas realmente está duplicado em essência com o método alunosPrograma.

Daria um não-na-massa essa mudança, não?

**Comment by masakik** [comment]
Bora agendar um meet.
