### ISSUE TITLE
Na classe Pessoa, corrigir no método telefones o campo que foi excluído.

### ISSUE THREAD

**Issue by ricardfo** [uspdev/replicado#43]
Corrigir o método de acordo com o DAE_14082018.
Corrigir também no replicado_queries.

**Comment by alecostaweb** [comment]
No gitlab uspdev/replicado_queries, sugiro torcar todas as tabelas por NOME-DA-TABELA.*, desta forma inclusões, alterações e exclusões de colunas nas tabelas passarão despercebidas.

**Comment by alecostaweb** [comment]
Até mesmo se incluir no gitlab uspdev/replicado_queries todas as tabelas do replicado com o NOME-DA-TABELA.* iria resolver, pois as tabelas só seriam utilizadas nos métodos criados no github uspdev/replicado. Desta forma, o replicado_queries só seria alterado quando tivesse exclusão ou inclusão de tabelas, ou seja, acredito que muito pouco. Vou abrir issue lá no replicado_queries.
