### ISSUE TITLE
No método vinculosSetores considerar o codundclg = 84

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/replicado#520]
O codundclg 84 corresponde a por exemplo alunos de Pós-Graduação do programa PROLAM (FE/FEA/FFLCH/FD/ECA).
Aqui na ECA é fundamental para os alunos nessa situação acessem a sala de Pesquisa através do uspdev/web-ldap-admin

**Comment by masakik** [comment]
Não é só colocar ele no env REPLICADO_CODUNDCLG junto com os outros códigos de unidade?

**Comment by alecostaweb** [comment]
Desde que o método esteja preparado para receber uma string do tipo codundclg IN (codund, 84)
