### ISSUE TITLE
falhar graciosamente quando a configuração estiver incompleta

### ISSUE THREAD

**Issue by wgnann** [uspdev/replicado#553]
hoje ele entrega um die() e mata o `composer install`. o ideal seria dar um aviso e continuar a instalação

**Comment by wgnann** [comment]
https://github.com/uspdev/replicado/blob/ed0c4832218c300f926602157a98d586a9d1f3fe/src/Replicado.php#L157

**Comment by wgnann** [comment]
Não sei se quebra algo, pois desconheço o funcionamento do uspdev/replicado.

Se não quebrar, pode ser uma boa.

**Comment by masakik** [comment]
Além do replicado não funcionar? Podemos deixar o log somente, e nenhuma mensagem. Como era anteriormente.
