### ISSUE TITLE
Mudar o método da consulta da classe DB

### ISSUE THREAD

**Issue by ricardfo** [uspdev/replicado#57]
Estamos utilizando o PDO com o método ->query($sql) já com os parâmetros, o ideal seria usar com bindParams do PDO, assim evitando sql injection.
Mas isso mudaria um pouco todas as consultas que temos hoje.
@alecostaweb  @thiagogomesverissimo @sybgroff

**Comment by alecostaweb** [comment]
Seria algo como:
```php
/* Execute a prepared statement by binding PHP variables */
$calories = 150;
$colour = 'red';
$sth = $dbh->prepare('SELECT name, colour, calories
    FROM fruit
    WHERE calories < :calories AND colour = :colour');
$sth->bindParam(':calories', $calories, PDO::PARAM_INT);
$sth->bindParam(':colour', $colour, PDO::PARAM_STR, 12);
$sth->execute();
```

**Comment by alecostaweb** [comment]
Bora mudar isso... Quem será que usa o uspdev/replicado além dos citados?

**Comment by thiagogomesverissimo** [comment]
Na real não quebra quem está usando (viva a abstração), pois na ponta o resultado será o mesmo. A questão é adotar uma padrão de projeto. Eu voto pela mudança, mas não consigo fazer pela questão de tempo.

**Comment by ricardfo** [comment]
Eu vou fazer a mudança.
