### ISSUE TITLE
O método ativos() da classe graduação está muito mais charmoso que o da Posgraduacao. Fazer igual.

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#66]

**Comment by alecostaweb** [comment]
@masakik o que quis dizer com "charmoso"?
Preciso exatamente o contrário, que o método Graduacao::ativos traga as mesmas colunas que o Posgraduacao::ativos. Até abri uma #187 
@thiagogomesverissimo a #73 faz sentido, poderia ser Pessoa::ativos($vinculo)
Ou preferem que eu crie este novo método?

**Comment by alecostaweb** [comment]
Estou pensando até em criar um método Pessoa::vinculos que retorna os vínculos possíveis através da consulta
SELECT DISTINCT tipvinext FROM ECA.dbo.LOCALIZAPESSOA WHERE sitatl = 'A' ORDER BY tipvinext

**Comment by alecostaweb** [comment]
Criei 2 métodos novos para que as aplicações já criadas não quebrem
