### ISSUE TITLE
Utilizar o convert para código de unidade (codundclg) quando houver consulta na tabela LOCALIZAPESSOA

### ISSUE THREAD

**Issue by sybgroff** [uspdev/replicado#76]
Verificamos que no caso de sybase é preciso usar o convert para converter para int o código da unidade, exemplo:

    $query .= " AND LOCALIZAPESSOA.codundclg = convert(int,:codundclgi) AND LOCALIZAPESSOA.sitatl = 'A') ";

**Comment by thiagogomesverissimo** [comment]
@alecostaweb 
você pode testar essa mudança de converter para inteiro o código da unidade no mssql, pois no sybase linux/windows ela funciona e no linux somo obrigados a fazer a conversão.
De:

`LOCALIZAPESSOA.codundclg = :codundclgi`
para

`LOCALIZAPESSOA.codundclg = convert(int,:codundclgi) `

**Comment by alecostaweb** [comment]
@thiagogomesverissimo 
Fiz o teste no módulo Graduacao que uso bastante no ccg e funcionou perfeitamente.
As mudanças já estão engatilhadas aí, ou quer que eu faça por aqui em todos os módulos?

**Comment by acesarfs** [comment]
@alecostaweb
Conversando com o Thiago, resolvemos fazer por aqui mesmo.

**Comment by alecostaweb** [comment]
Blz, já ia mandar um sed na pasta src. Vlw :+1:
