### ISSUE TITLE
No módulo estagiarios talvez alterar campo do tipo de vínculo

### ISSUE THREAD

**Issue by sybgroff** [uspdev/replicado#77]
No caso dos estagiários, podemos alterar
de
`
$query .= " WHERE (LOCALIZAPESSOA.tipvinext LIKE 'Estagiario' ";`

para
`
$query .= " WHERE (LOCALIZAPESSOA.tipvin LIKE 'ESTAGIARIORH' ";`

pois o campo `tipvinext` está com acento 'Estagiário'.

**Comment by lfloro** [comment]
Acredito que o @thiagogomesverissimo resolveu essa _issue_ [aqui] (https://github.com/uspdev/replicado/commit/6dcfa35fdb7e906b61305e0b331a0436e4f0627d#diff-a450d0369e832c0d563723391e115744)

**Comment by lfloro** [comment]
Acredito que o @thiagogomesverissimo resolveu essa _issue_ [https://github.com/uspdev/replicado/commit/6dcfa35fdb7e906b61305e0b331a0436e4f0627d#diff-a450d0369e832c0d563723391e115744] (aqui)

**Comment by lfloro** [comment]
Acredito que o @thiagogomesverissimo resolveu essa _issue_ [aqui](https://github.com/uspdev/replicado/commit/6dcfa35fdb7e906b61305e0b331a0436e4f0627d#diff-a450d0369e832c0d563723391e115744)

**Comment by thiagogomesverissimo** [comment]
Isso =)
