### ISSUE TITLE
log do monolog gerando erro de gravação

### ISSUE THREAD

**Issue by masakik** [uspdev/replicado#81]
O porjeto tenta gravar o arquivo de log na pasta do composer e assim gera erro de escrita. Acho que deveria ficar em uma pasta fora configurável.

There is no existing directory at ".../replicado-teste/vendor/uspdev/replicado/src/log" and its not buildable: Permission denied in .../replicado-teste/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php

**Comment by thiagogomesverissimo** [comment]
Podemos deixar o caminho da pasta para log configurável no momento do instanciamento da classe.
@ricardfo
