### ISSUE TITLE
Método que retorna apenas funcionários

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#96]
`select * FROM LOCALIZAPESSOA where tipvin like '%SERVIDOR%' and sitatl='A' and tipvinext not like '%Docente%' and codundclg=8 and codfncetr = 0;`

o campo codfncetr = 0 serve para não trazer designações;

**Comment by thiagogomesverissimo** [comment]
Se quisermos e-mails:

`select * FROM LOCALIZAPESSOA INNER JOIN EMAILPESSOA ON (LOCALIZAPESSOA.codpes = EMAILPESSOA.codpes) where tipvin like '%SERVIDOR%' and sitatl='A' and tipvinext not like '%Docente%' and codundclg=8 and codfncetr = 0  and stamtr='S' ;`

**Comment by masakik** [comment]
Compensa colocar a opção de setor?

**Comment by alecostaweb** [comment]
Na tabela LOCALIZAPESSOA já tem codset, codabvset e nomset. A opção de setor seria o filtro? Seria interessante também outros filtros? Por exemplo aposentados (sitatl = 'P'), informática (nomset LIKE '$informática%'), designados, etc.

**Comment by masakik** [comment]
No caso de docentes que tem permanência onde entraria? Na lista de docentes poderia ter á opção de incluir oi não esses com permanência. Agora aposentados inativos não sei como poderia ser  á utilizacao. Caso de funcionários seriam somente os autárquicos que os celetistas saem da folha. Agora pode ter docente inativo mas que está credenciado na pg.
